
   
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"

  # La siguiente configuración de la red será ignorada si utilizas hyperv
  # Más información: https://www.vagrantup.com/docs/providers/hyperv/limitations#limited-networking
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end
  
  config.vm.provider "hyperv" do |hv|
    hv.memory = "2048"
    hv.cpus = 2
  end
  
  # Script de aprovisionamiento de la máquina virtual.
  # Instala Java 11 y Jenkins utilizando apt
  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    apt update
    apt install -y openjdk-11-jre
    apt install -y jenkins
    apt install -y git zip unzip make gcc
    apt upgrade 
  SHELL
end
